import React from 'react';
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { ConfigProvider } from "antd";
import theme from "@/theme/themeConfig";
import './globals.css';
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
          <main className='bg-[#f7f7f7] min-h-screen flex items-center flex-col '>

            <Navbar/>
            <div className='max-lg:w-full lg:w-4/5 pb-8'>
              {children}

            </div>
          </main>
        
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
